spring:
  datasource:
    username: music_library
    password: music_library
    url: jdbc:mysql://localhost:3306/music_library


  jpa:
    hibernate:
      ddl-auto: update # creates/updates tables automatically
    show-sql: true
    defer-datasource-initialization: true
    
  sql:
    init: 
      mode: never # if not loading any .sql scripts at startup