INSERT INTO breed (name) VALUES ('Bulldog');
INSERT INTO breed (name) VALUES ('Golden Retriever');
INSERT INTO breed (name) VALUES ('German Shepherd');
INSERT INTO breed (name) VALUES ('GoldenDoodle');
INSERT INTO breed (name) VALUES ('LabraDoodle');
INSERT INTO breed (name) VALUES ('Poodle');
INSERT INTO breed (name) VALUES ('Beagle');
INSERT INTO breed (name) VALUES ('Boxer');
INSERT INTO breed (name) VALUES ('Cocker Spaniel');
INSERT INTO breed (name) VALUES ('Dachshund');
INSERT INTO breed (name) VALUES ('French Bulldog');
INSERT INTO breed (name) VALUES ('Great Dane');
INSERT INTO breed (name) VALUES ('Husky');
INSERT INTO breed (name) VALUES ('Maltese');
INSERT INTO breed (name) VALUES ('Miniature Schnauzer');
INSERT INTO breed (name) VALUES ('Pomeranian');
INSERT INTO breed (name) VALUES ('Rottweiler');
INSERT INTO breed (name) VALUES ('Shih Tzu');
INSERT INTO breed (name) VALUES ('Siberian Husky');
INSERT INTO breed (name) VALUES ('Yorkshire Terrier');
INSERT INTO breed (name) VALUES ('Australian Shepherd');
INSERT INTO breed (name) VALUES ('Bernese Mountain Dog');
INSERT INTO breed (name) VALUES ('Chihuahua');
INSERT INTO breed (name) VALUES ('Collie');
INSERT INTO breed (name) VALUES ('English Springer Spaniel');
INSERT INTO breed (name) VALUES ('Irish Setter');
INSERT INTO breed (name) VALUES ('Jack Russell Terrier');
INSERT INTO breed (name) VALUES ('Labrador Retriever');
INSERT INTO breed (name) VALUES ('Mastiff');
INSERT INTO breed (name) VALUES ('Newfoundland');
INSERT INTO breed (name) VALUES ('Papillon');
INSERT INTO breed (name) VALUES ('Pit Bull Terrier');
INSERT INTO breed (name) VALUES ('Samoyed');
INSERT INTO breed (name) VALUES ('Weimaraner');
INSERT INTO breed (name) VALUES ('West Highland White Terrier');
INSERT INTO breed (name) VALUES ('Whippet');
INSERT INTO breed (name) VALUES ('Alaskan Malamute');
INSERT INTO breed (name) VALUES ('Bichon Frise');
INSERT INTO breed (name) VALUES ('Bloodhound');
INSERT INTO breed (name) VALUES ('Border Collie');
INSERT INTO breed (name) VALUES ('Bull Terrier');
INSERT INTO breed (name) VALUES ('Cavalier King Charles Spaniel');
INSERT INTO breed (name) VALUES ('Chinese Crested');
INSERT INTO breed (name) VALUES ('Doberman Pinscher');
INSERT INTO breed (name) VALUES ('English Bulldog');
INSERT INTO breed (name) VALUES ('Greyhound');
INSERT INTO breed (name) VALUES ('Havanese');
INSERT INTO breed (name) VALUES ('Italian Greyhound');
INSERT INTO breed (name) VALUES ('Lhasa Apso');
INSERT INTO breed (name) VALUES ('Manchester Terrier');
INSERT INTO breed (name) VALUES ('Old English Sheepdog');
INSERT INTO breed (name) VALUES ('Portuguese Water Dog');
INSERT INTO breed (name) VALUES ('Saluki');
INSERT INTO breed (name) VALUES ('Scottish Terrier');
INSERT INTO breed (name) VALUES ('Silky Terrier');
INSERT INTO breed (name) VALUES ('St. Bernard');
INSERT INTO breed (name) VALUES ('Tibetan Terrier');
INSERT INTO breed (name) VALUES ('Vizsla');
INSERT INTO breed (name) VALUES ('Welsh Corgi');
INSERT INTO breed (name) VALUES ('Xoloitzcuintli');
INSERT INTO breed (name) VALUES ('Yorkipoo');